name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test # will run `yarn test` command
      - name: Build React App
        run: yarn build

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./build demo-project-anwarb.surge.sh --token ${{ secrets.DEMO_TOKEN }}
